export interface LoLGeneratedChampionRecord {
  dataDragonId: string;
  riotKey: string;
  displayName: string;
  tags: readonly string[];
  localizedNames?: Readonly<Record<string, string>>;
}

export const LOL_GENERATED_CHAMPION_SOURCE = Object.freeze({
  dataDragonVersion: "16.11.1",
  language: "en_US",
  localizedLanguages: ["zh_TW"],
  localizedLocales: {"zh_TW":"zh-TW"},
  localizedNameCoverage: {"zh-TW":172},
  importedAt: "2026-06-03",
  importSource: "Riot Data Dragon champion.json static data",
  localIconPathConvention: "assets/hero-icons/lol/<ChampionDataId>.png",
  localSquarePathConvention: "assets/hero-icons/lol/<ChampionDataId>.png",
  approvedArtworkIncluded: false
});

export const LOL_GENERATED_CHAMPION_RECORDS = [
  { dataDragonId: "Aatrox", riotKey: "266", displayName: "Aatrox", tags: ["Fighter"], localizedNames: {"zh-TW":"厄薩斯"} },
  { dataDragonId: "Ahri", riotKey: "103", displayName: "Ahri", tags: ["Mage","Assassin"], localizedNames: {"zh-TW":"阿璃"} },
  { dataDragonId: "Akali", riotKey: "84", displayName: "Akali", tags: ["Assassin"], localizedNames: {"zh-TW":"阿卡莉"} },
  { dataDragonId: "Akshan", riotKey: "166", displayName: "Akshan", tags: ["Marksman","Assassin"], localizedNames: {"zh-TW":"埃可尚"} },
  { dataDragonId: "Alistar", riotKey: "12", displayName: "Alistar", tags: ["Tank","Support"], localizedNames: {"zh-TW":"亞歷斯塔"} },
  { dataDragonId: "Ambessa", riotKey: "799", displayName: "Ambessa", tags: ["Fighter","Assassin"], localizedNames: {"zh-TW":"安比薩"} },
  { dataDragonId: "Amumu", riotKey: "32", displayName: "Amumu", tags: ["Tank","Support"], localizedNames: {"zh-TW":"阿姆姆"} },
  { dataDragonId: "Anivia", riotKey: "34", displayName: "Anivia", tags: ["Mage"], localizedNames: {"zh-TW":"艾妮維亞"} },
  { dataDragonId: "Annie", riotKey: "1", displayName: "Annie", tags: ["Mage","Support"], localizedNames: {"zh-TW":"安妮"} },
  { dataDragonId: "Aphelios", riotKey: "523", displayName: "Aphelios", tags: ["Marksman"], localizedNames: {"zh-TW":"亞菲利歐"} },
  { dataDragonId: "Ashe", riotKey: "22", displayName: "Ashe", tags: ["Marksman","Support"], localizedNames: {"zh-TW":"艾希"} },
  { dataDragonId: "AurelionSol", riotKey: "136", displayName: "Aurelion Sol", tags: ["Mage"], localizedNames: {"zh-TW":"翱銳龍獸"} },
  { dataDragonId: "Aurora", riotKey: "893", displayName: "Aurora", tags: ["Mage","Assassin"], localizedNames: {"zh-TW":"歐羅拉"} },
  { dataDragonId: "Azir", riotKey: "268", displayName: "Azir", tags: ["Mage","Marksman"], localizedNames: {"zh-TW":"阿祈爾"} },
  { dataDragonId: "Bard", riotKey: "432", displayName: "Bard", tags: ["Support","Mage"], localizedNames: {"zh-TW":"巴德"} },
  { dataDragonId: "Belveth", riotKey: "200", displayName: "Bel'Veth", tags: ["Fighter"], localizedNames: {"zh-TW":"貝爾薇斯"} },
  { dataDragonId: "Blitzcrank", riotKey: "53", displayName: "Blitzcrank", tags: ["Tank","Support"], localizedNames: {"zh-TW":"布里茨"} },
  { dataDragonId: "Brand", riotKey: "63", displayName: "Brand", tags: ["Mage","Support"], localizedNames: {"zh-TW":"布蘭德"} },
  { dataDragonId: "Braum", riotKey: "201", displayName: "Braum", tags: ["Tank","Support"], localizedNames: {"zh-TW":"布郎姆"} },
  { dataDragonId: "Briar", riotKey: "233", displayName: "Briar", tags: ["Fighter","Assassin"], localizedNames: {"zh-TW":"布蕾爾"} },
  { dataDragonId: "Caitlyn", riotKey: "51", displayName: "Caitlyn", tags: ["Marksman"], localizedNames: {"zh-TW":"凱特琳"} },
  { dataDragonId: "Camille", riotKey: "164", displayName: "Camille", tags: ["Fighter","Assassin"], localizedNames: {"zh-TW":"卡蜜兒"} },
  { dataDragonId: "Cassiopeia", riotKey: "69", displayName: "Cassiopeia", tags: ["Mage"], localizedNames: {"zh-TW":"卡莎碧雅"} },
  { dataDragonId: "Chogath", riotKey: "31", displayName: "Cho'Gath", tags: ["Tank","Mage"], localizedNames: {"zh-TW":"科加斯"} },
  { dataDragonId: "Corki", riotKey: "42", displayName: "Corki", tags: ["Marksman","Mage"], localizedNames: {"zh-TW":"庫奇"} },
  { dataDragonId: "Darius", riotKey: "122", displayName: "Darius", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"達瑞斯"} },
  { dataDragonId: "Diana", riotKey: "131", displayName: "Diana", tags: ["Fighter","Assassin"], localizedNames: {"zh-TW":"黛安娜"} },
  { dataDragonId: "DrMundo", riotKey: "36", displayName: "Dr. Mundo", tags: ["Tank","Fighter"], localizedNames: {"zh-TW":"蒙多醫生"} },
  { dataDragonId: "Draven", riotKey: "119", displayName: "Draven", tags: ["Marksman"], localizedNames: {"zh-TW":"達瑞文"} },
  { dataDragonId: "Ekko", riotKey: "245", displayName: "Ekko", tags: ["Assassin","Mage"], localizedNames: {"zh-TW":"艾克"} },
  { dataDragonId: "Elise", riotKey: "60", displayName: "Elise", tags: ["Assassin","Mage"], localizedNames: {"zh-TW":"伊莉絲"} },
  { dataDragonId: "Evelynn", riotKey: "28", displayName: "Evelynn", tags: ["Assassin","Mage"], localizedNames: {"zh-TW":"伊芙琳"} },
  { dataDragonId: "Ezreal", riotKey: "81", displayName: "Ezreal", tags: ["Marksman","Mage"], localizedNames: {"zh-TW":"伊澤瑞爾"} },
  { dataDragonId: "Fiddlesticks", riotKey: "9", displayName: "Fiddlesticks", tags: ["Mage","Support"], localizedNames: {"zh-TW":"費德提克"} },
  { dataDragonId: "Fiora", riotKey: "114", displayName: "Fiora", tags: ["Fighter","Assassin"], localizedNames: {"zh-TW":"菲歐拉"} },
  { dataDragonId: "Fizz", riotKey: "105", displayName: "Fizz", tags: ["Assassin","Fighter"], localizedNames: {"zh-TW":"飛斯"} },
  { dataDragonId: "Galio", riotKey: "3", displayName: "Galio", tags: ["Tank","Mage"], localizedNames: {"zh-TW":"加里歐"} },
  { dataDragonId: "Gangplank", riotKey: "41", displayName: "Gangplank", tags: ["Fighter"], localizedNames: {"zh-TW":"剛普朗克"} },
  { dataDragonId: "Garen", riotKey: "86", displayName: "Garen", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"蓋倫"} },
  { dataDragonId: "Gnar", riotKey: "150", displayName: "Gnar", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"吶兒"} },
  { dataDragonId: "Gragas", riotKey: "79", displayName: "Gragas", tags: ["Fighter","Mage"], localizedNames: {"zh-TW":"古拉格斯"} },
  { dataDragonId: "Graves", riotKey: "104", displayName: "Graves", tags: ["Marksman"], localizedNames: {"zh-TW":"葛雷夫"} },
  { dataDragonId: "Gwen", riotKey: "887", displayName: "Gwen", tags: ["Fighter"], localizedNames: {"zh-TW":"關"} },
  { dataDragonId: "Hecarim", riotKey: "120", displayName: "Hecarim", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"赫克林"} },
  { dataDragonId: "Heimerdinger", riotKey: "74", displayName: "Heimerdinger", tags: ["Mage","Support"], localizedNames: {"zh-TW":"漢默丁格"} },
  { dataDragonId: "Hwei", riotKey: "910", displayName: "Hwei", tags: ["Mage","Support"], localizedNames: {"zh-TW":"赫威"} },
  { dataDragonId: "Illaoi", riotKey: "420", displayName: "Illaoi", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"伊羅旖"} },
  { dataDragonId: "Irelia", riotKey: "39", displayName: "Irelia", tags: ["Fighter","Assassin"], localizedNames: {"zh-TW":"伊瑞莉雅"} },
  { dataDragonId: "Ivern", riotKey: "427", displayName: "Ivern", tags: ["Support","Mage"], localizedNames: {"zh-TW":"埃爾文"} },
  { dataDragonId: "Janna", riotKey: "40", displayName: "Janna", tags: ["Support","Mage"], localizedNames: {"zh-TW":"珍娜"} },
  { dataDragonId: "JarvanIV", riotKey: "59", displayName: "Jarvan IV", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"嘉文四世"} },
  { dataDragonId: "Jax", riotKey: "24", displayName: "Jax", tags: ["Fighter"], localizedNames: {"zh-TW":"賈克斯"} },
  { dataDragonId: "Jayce", riotKey: "126", displayName: "Jayce", tags: ["Fighter","Marksman"], localizedNames: {"zh-TW":"杰西"} },
  { dataDragonId: "Jhin", riotKey: "202", displayName: "Jhin", tags: ["Marksman","Mage"], localizedNames: {"zh-TW":"燼"} },
  { dataDragonId: "Jinx", riotKey: "222", displayName: "Jinx", tags: ["Marksman"], localizedNames: {"zh-TW":"吉茵珂絲"} },
  { dataDragonId: "KSante", riotKey: "897", displayName: "K'Sante", tags: ["Tank","Fighter"], localizedNames: {"zh-TW":"卡桑帝"} },
  { dataDragonId: "Kaisa", riotKey: "145", displayName: "Kai'Sa", tags: ["Marksman","Mage"], localizedNames: {"zh-TW":"凱莎"} },
  { dataDragonId: "Kalista", riotKey: "429", displayName: "Kalista", tags: ["Marksman"], localizedNames: {"zh-TW":"克黎思妲"} },
  { dataDragonId: "Karma", riotKey: "43", displayName: "Karma", tags: ["Mage","Support"], localizedNames: {"zh-TW":"卡瑪"} },
  { dataDragonId: "Karthus", riotKey: "30", displayName: "Karthus", tags: ["Mage"], localizedNames: {"zh-TW":"卡爾瑟斯"} },
  { dataDragonId: "Kassadin", riotKey: "38", displayName: "Kassadin", tags: ["Assassin","Mage"], localizedNames: {"zh-TW":"卡薩丁"} },
  { dataDragonId: "Katarina", riotKey: "55", displayName: "Katarina", tags: ["Assassin","Mage"], localizedNames: {"zh-TW":"卡特蓮娜"} },
  { dataDragonId: "Kayle", riotKey: "10", displayName: "Kayle", tags: ["Mage","Marksman"], localizedNames: {"zh-TW":"凱爾"} },
  { dataDragonId: "Kayn", riotKey: "141", displayName: "Kayn", tags: ["Fighter","Assassin"], localizedNames: {"zh-TW":"慨影"} },
  { dataDragonId: "Kennen", riotKey: "85", displayName: "Kennen", tags: ["Mage"], localizedNames: {"zh-TW":"凱能"} },
  { dataDragonId: "Khazix", riotKey: "121", displayName: "Kha'Zix", tags: ["Assassin"], localizedNames: {"zh-TW":"卡力斯"} },
  { dataDragonId: "Kindred", riotKey: "203", displayName: "Kindred", tags: ["Marksman"], localizedNames: {"zh-TW":"鏡爪"} },
  { dataDragonId: "Kled", riotKey: "240", displayName: "Kled", tags: ["Fighter"], localizedNames: {"zh-TW":"克雷德"} },
  { dataDragonId: "KogMaw", riotKey: "96", displayName: "Kog'Maw", tags: ["Marksman","Mage"], localizedNames: {"zh-TW":"寇格魔"} },
  { dataDragonId: "Leblanc", riotKey: "7", displayName: "LeBlanc", tags: ["Assassin","Mage"], localizedNames: {"zh-TW":"勒布朗"} },
  { dataDragonId: "LeeSin", riotKey: "64", displayName: "Lee Sin", tags: ["Fighter","Assassin"], localizedNames: {"zh-TW":"李星"} },
  { dataDragonId: "Leona", riotKey: "89", displayName: "Leona", tags: ["Tank","Support"], localizedNames: {"zh-TW":"雷歐娜"} },
  { dataDragonId: "Lillia", riotKey: "876", displayName: "Lillia", tags: ["Fighter","Mage"], localizedNames: {"zh-TW":"莉莉亞"} },
  { dataDragonId: "Lissandra", riotKey: "127", displayName: "Lissandra", tags: ["Mage"], localizedNames: {"zh-TW":"麗珊卓"} },
  { dataDragonId: "Lucian", riotKey: "236", displayName: "Lucian", tags: ["Marksman","Assassin"], localizedNames: {"zh-TW":"路西恩"} },
  { dataDragonId: "Lulu", riotKey: "117", displayName: "Lulu", tags: ["Support","Mage"], localizedNames: {"zh-TW":"露璐"} },
  { dataDragonId: "Lux", riotKey: "99", displayName: "Lux", tags: ["Mage","Support"], localizedNames: {"zh-TW":"拉克絲"} },
  { dataDragonId: "Malphite", riotKey: "54", displayName: "Malphite", tags: ["Tank","Mage"], localizedNames: {"zh-TW":"墨菲特"} },
  { dataDragonId: "Malzahar", riotKey: "90", displayName: "Malzahar", tags: ["Mage"], localizedNames: {"zh-TW":"馬爾札哈"} },
  { dataDragonId: "Maokai", riotKey: "57", displayName: "Maokai", tags: ["Tank","Support"], localizedNames: {"zh-TW":"茂凱"} },
  { dataDragonId: "MasterYi", riotKey: "11", displayName: "Master Yi", tags: ["Fighter","Assassin"], localizedNames: {"zh-TW":"易大師"} },
  { dataDragonId: "Mel", riotKey: "800", displayName: "Mel", tags: ["Mage","Support"], localizedNames: {"zh-TW":"梅爾"} },
  { dataDragonId: "Milio", riotKey: "902", displayName: "Milio", tags: ["Support","Mage"], localizedNames: {"zh-TW":"米里歐"} },
  { dataDragonId: "MissFortune", riotKey: "21", displayName: "Miss Fortune", tags: ["Marksman","Mage"], localizedNames: {"zh-TW":"好運姐"} },
  { dataDragonId: "Mordekaiser", riotKey: "82", displayName: "Mordekaiser", tags: ["Fighter","Mage"], localizedNames: {"zh-TW":"魔鬥凱薩"} },
  { dataDragonId: "Morgana", riotKey: "25", displayName: "Morgana", tags: ["Support","Mage"], localizedNames: {"zh-TW":"魔甘娜"} },
  { dataDragonId: "Naafiri", riotKey: "950", displayName: "Naafiri", tags: ["Assassin","Fighter"], localizedNames: {"zh-TW":"娜菲芮"} },
  { dataDragonId: "Nami", riotKey: "267", displayName: "Nami", tags: ["Support","Mage"], localizedNames: {"zh-TW":"娜米"} },
  { dataDragonId: "Nasus", riotKey: "75", displayName: "Nasus", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"納瑟斯"} },
  { dataDragonId: "Nautilus", riotKey: "111", displayName: "Nautilus", tags: ["Tank","Support"], localizedNames: {"zh-TW":"納帝魯斯"} },
  { dataDragonId: "Neeko", riotKey: "518", displayName: "Neeko", tags: ["Mage","Support"], localizedNames: {"zh-TW":"妮可"} },
  { dataDragonId: "Nidalee", riotKey: "76", displayName: "Nidalee", tags: ["Assassin","Mage"], localizedNames: {"zh-TW":"奈德麗"} },
  { dataDragonId: "Nilah", riotKey: "895", displayName: "Nilah", tags: ["Fighter","Assassin"], localizedNames: {"zh-TW":"淣菈"} },
  { dataDragonId: "Nocturne", riotKey: "56", displayName: "Nocturne", tags: ["Fighter","Assassin"], localizedNames: {"zh-TW":"夜曲"} },
  { dataDragonId: "Nunu", riotKey: "20", displayName: "Nunu & Willump", tags: ["Tank","Mage"], localizedNames: {"zh-TW":"努努和威朗普"} },
  { dataDragonId: "Olaf", riotKey: "2", displayName: "Olaf", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"歐拉夫"} },
  { dataDragonId: "Orianna", riotKey: "61", displayName: "Orianna", tags: ["Mage","Support"], localizedNames: {"zh-TW":"奧莉安娜"} },
  { dataDragonId: "Ornn", riotKey: "516", displayName: "Ornn", tags: ["Tank"], localizedNames: {"zh-TW":"鄂爾"} },
  { dataDragonId: "Pantheon", riotKey: "80", displayName: "Pantheon", tags: ["Fighter","Assassin"], localizedNames: {"zh-TW":"潘森"} },
  { dataDragonId: "Poppy", riotKey: "78", displayName: "Poppy", tags: ["Tank","Fighter"], localizedNames: {"zh-TW":"波比"} },
  { dataDragonId: "Pyke", riotKey: "555", displayName: "Pyke", tags: ["Support","Assassin"], localizedNames: {"zh-TW":"派克"} },
  { dataDragonId: "Qiyana", riotKey: "246", displayName: "Qiyana", tags: ["Assassin"], localizedNames: {"zh-TW":"姬亞娜"} },
  { dataDragonId: "Quinn", riotKey: "133", displayName: "Quinn", tags: ["Marksman","Assassin"], localizedNames: {"zh-TW":"葵恩"} },
  { dataDragonId: "Rakan", riotKey: "497", displayName: "Rakan", tags: ["Support"], localizedNames: {"zh-TW":"銳空"} },
  { dataDragonId: "Rammus", riotKey: "33", displayName: "Rammus", tags: ["Tank"], localizedNames: {"zh-TW":"拉姆斯"} },
  { dataDragonId: "RekSai", riotKey: "421", displayName: "Rek'Sai", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"雷珂煞"} },
  { dataDragonId: "Rell", riotKey: "526", displayName: "Rell", tags: ["Tank","Support"], localizedNames: {"zh-TW":"銳兒"} },
  { dataDragonId: "Renata", riotKey: "888", displayName: "Renata Glasc", tags: ["Support","Mage"], localizedNames: {"zh-TW":"睿娜妲‧格萊斯克"} },
  { dataDragonId: "Renekton", riotKey: "58", displayName: "Renekton", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"雷尼克頓"} },
  { dataDragonId: "Rengar", riotKey: "107", displayName: "Rengar", tags: ["Assassin","Fighter"], localizedNames: {"zh-TW":"雷葛爾"} },
  { dataDragonId: "Riven", riotKey: "92", displayName: "Riven", tags: ["Fighter","Assassin"], localizedNames: {"zh-TW":"雷玟"} },
  { dataDragonId: "Rumble", riotKey: "68", displayName: "Rumble", tags: ["Fighter","Mage"], localizedNames: {"zh-TW":"藍寶"} },
  { dataDragonId: "Ryze", riotKey: "13", displayName: "Ryze", tags: ["Mage"], localizedNames: {"zh-TW":"雷茲"} },
  { dataDragonId: "Samira", riotKey: "360", displayName: "Samira", tags: ["Marksman","Assassin"], localizedNames: {"zh-TW":"煞蜜拉"} },
  { dataDragonId: "Sejuani", riotKey: "113", displayName: "Sejuani", tags: ["Tank"], localizedNames: {"zh-TW":"史瓦妮"} },
  { dataDragonId: "Senna", riotKey: "235", displayName: "Senna", tags: ["Support","Marksman"], localizedNames: {"zh-TW":"姍娜"} },
  { dataDragonId: "Seraphine", riotKey: "147", displayName: "Seraphine", tags: ["Support","Mage"], localizedNames: {"zh-TW":"瑟菈紛"} },
  { dataDragonId: "Sett", riotKey: "875", displayName: "Sett", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"賽特"} },
  { dataDragonId: "Shaco", riotKey: "35", displayName: "Shaco", tags: ["Assassin"], localizedNames: {"zh-TW":"薩科"} },
  { dataDragonId: "Shen", riotKey: "98", displayName: "Shen", tags: ["Tank"], localizedNames: {"zh-TW":"慎"} },
  { dataDragonId: "Shyvana", riotKey: "102", displayName: "Shyvana", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"希瓦娜"} },
  { dataDragonId: "Singed", riotKey: "27", displayName: "Singed", tags: ["Tank","Mage"], localizedNames: {"zh-TW":"辛吉德"} },
  { dataDragonId: "Sion", riotKey: "14", displayName: "Sion", tags: ["Tank","Fighter"], localizedNames: {"zh-TW":"賽恩"} },
  { dataDragonId: "Sivir", riotKey: "15", displayName: "Sivir", tags: ["Marksman"], localizedNames: {"zh-TW":"希維爾"} },
  { dataDragonId: "Skarner", riotKey: "72", displayName: "Skarner", tags: ["Tank","Fighter"], localizedNames: {"zh-TW":"史加納"} },
  { dataDragonId: "Smolder", riotKey: "901", displayName: "Smolder", tags: ["Marksman","Mage"], localizedNames: {"zh-TW":"史矛德"} },
  { dataDragonId: "Sona", riotKey: "37", displayName: "Sona", tags: ["Support","Mage"], localizedNames: {"zh-TW":"索娜"} },
  { dataDragonId: "Soraka", riotKey: "16", displayName: "Soraka", tags: ["Support","Mage"], localizedNames: {"zh-TW":"索拉卡"} },
  { dataDragonId: "Swain", riotKey: "50", displayName: "Swain", tags: ["Mage","Support"], localizedNames: {"zh-TW":"斯溫"} },
  { dataDragonId: "Sylas", riotKey: "517", displayName: "Sylas", tags: ["Mage","Assassin"], localizedNames: {"zh-TW":"賽勒斯"} },
  { dataDragonId: "Syndra", riotKey: "134", displayName: "Syndra", tags: ["Mage"], localizedNames: {"zh-TW":"星朵拉"} },
  { dataDragonId: "TahmKench", riotKey: "223", displayName: "Tahm Kench", tags: ["Tank","Support"], localizedNames: {"zh-TW":"貪啃奇"} },
  { dataDragonId: "Taliyah", riotKey: "163", displayName: "Taliyah", tags: ["Mage","Support"], localizedNames: {"zh-TW":"塔莉雅"} },
  { dataDragonId: "Talon", riotKey: "91", displayName: "Talon", tags: ["Assassin"], localizedNames: {"zh-TW":"塔隆"} },
  { dataDragonId: "Taric", riotKey: "44", displayName: "Taric", tags: ["Support","Tank"], localizedNames: {"zh-TW":"塔里克"} },
  { dataDragonId: "Teemo", riotKey: "17", displayName: "Teemo", tags: ["Marksman","Mage"], localizedNames: {"zh-TW":"提摩"} },
  { dataDragonId: "Thresh", riotKey: "412", displayName: "Thresh", tags: ["Support","Tank"], localizedNames: {"zh-TW":"瑟雷西"} },
  { dataDragonId: "Tristana", riotKey: "18", displayName: "Tristana", tags: ["Marksman","Assassin"], localizedNames: {"zh-TW":"崔絲塔娜"} },
  { dataDragonId: "Trundle", riotKey: "48", displayName: "Trundle", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"特朗德"} },
  { dataDragonId: "Tryndamere", riotKey: "23", displayName: "Tryndamere", tags: ["Fighter","Assassin"], localizedNames: {"zh-TW":"泰達米爾"} },
  { dataDragonId: "TwistedFate", riotKey: "4", displayName: "Twisted Fate", tags: ["Mage","Marksman"], localizedNames: {"zh-TW":"逆命"} },
  { dataDragonId: "Twitch", riotKey: "29", displayName: "Twitch", tags: ["Marksman","Assassin"], localizedNames: {"zh-TW":"圖奇"} },
  { dataDragonId: "Udyr", riotKey: "77", displayName: "Udyr", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"烏迪爾"} },
  { dataDragonId: "Urgot", riotKey: "6", displayName: "Urgot", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"烏爾加特"} },
  { dataDragonId: "Varus", riotKey: "110", displayName: "Varus", tags: ["Marksman","Mage"], localizedNames: {"zh-TW":"法洛士"} },
  { dataDragonId: "Vayne", riotKey: "67", displayName: "Vayne", tags: ["Marksman","Assassin"], localizedNames: {"zh-TW":"汎"} },
  { dataDragonId: "Veigar", riotKey: "45", displayName: "Veigar", tags: ["Mage"], localizedNames: {"zh-TW":"維迦"} },
  { dataDragonId: "Velkoz", riotKey: "161", displayName: "Vel'Koz", tags: ["Mage","Support"], localizedNames: {"zh-TW":"威寇茲"} },
  { dataDragonId: "Vex", riotKey: "711", displayName: "Vex", tags: ["Mage"], localizedNames: {"zh-TW":"薇可絲"} },
  { dataDragonId: "Vi", riotKey: "254", displayName: "Vi", tags: ["Fighter","Assassin"], localizedNames: {"zh-TW":"菲艾"} },
  { dataDragonId: "Viego", riotKey: "234", displayName: "Viego", tags: ["Fighter","Assassin"], localizedNames: {"zh-TW":"維爾戈"} },
  { dataDragonId: "Viktor", riotKey: "112", displayName: "Viktor", tags: ["Mage"], localizedNames: {"zh-TW":"維克特"} },
  { dataDragonId: "Vladimir", riotKey: "8", displayName: "Vladimir", tags: ["Mage","Fighter"], localizedNames: {"zh-TW":"弗拉迪米爾"} },
  { dataDragonId: "Volibear", riotKey: "106", displayName: "Volibear", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"弗力貝爾"} },
  { dataDragonId: "Warwick", riotKey: "19", displayName: "Warwick", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"沃維克"} },
  { dataDragonId: "MonkeyKing", riotKey: "62", displayName: "Wukong", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"悟空"} },
  { dataDragonId: "Xayah", riotKey: "498", displayName: "Xayah", tags: ["Marksman"], localizedNames: {"zh-TW":"剎雅"} },
  { dataDragonId: "Xerath", riotKey: "101", displayName: "Xerath", tags: ["Mage","Support"], localizedNames: {"zh-TW":"齊勒斯"} },
  { dataDragonId: "XinZhao", riotKey: "5", displayName: "Xin Zhao", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"趙信"} },
  { dataDragonId: "Yasuo", riotKey: "157", displayName: "Yasuo", tags: ["Fighter","Assassin"], localizedNames: {"zh-TW":"犽宿"} },
  { dataDragonId: "Yone", riotKey: "777", displayName: "Yone", tags: ["Fighter","Assassin"], localizedNames: {"zh-TW":"犽凝"} },
  { dataDragonId: "Yorick", riotKey: "83", displayName: "Yorick", tags: ["Fighter","Tank"], localizedNames: {"zh-TW":"約瑞科"} },
  { dataDragonId: "Yunara", riotKey: "804", displayName: "Yunara", tags: ["Marksman"], localizedNames: {"zh-TW":"尤娜拉"} },
  { dataDragonId: "Yuumi", riotKey: "350", displayName: "Yuumi", tags: ["Support","Mage"], localizedNames: {"zh-TW":"悠咪"} },
  { dataDragonId: "Zaahen", riotKey: "904", displayName: "Zaahen", tags: ["Fighter","Assassin"], localizedNames: {"zh-TW":"薩亨"} },
  { dataDragonId: "Zac", riotKey: "154", displayName: "Zac", tags: ["Tank","Fighter"], localizedNames: {"zh-TW":"札克"} },
  { dataDragonId: "Zed", riotKey: "238", displayName: "Zed", tags: ["Assassin"], localizedNames: {"zh-TW":"劫"} },
  { dataDragonId: "Zeri", riotKey: "221", displayName: "Zeri", tags: ["Marksman"], localizedNames: {"zh-TW":"婕莉"} },
  { dataDragonId: "Ziggs", riotKey: "115", displayName: "Ziggs", tags: ["Mage"], localizedNames: {"zh-TW":"希格斯"} },
  { dataDragonId: "Zilean", riotKey: "26", displayName: "Zilean", tags: ["Support","Mage"], localizedNames: {"zh-TW":"極靈"} },
  { dataDragonId: "Zoe", riotKey: "142", displayName: "Zoe", tags: ["Mage"], localizedNames: {"zh-TW":"柔依"} },
  { dataDragonId: "Zyra", riotKey: "143", displayName: "Zyra", tags: ["Mage","Support"], localizedNames: {"zh-TW":"枷蘿"} }
] as const satisfies readonly LoLGeneratedChampionRecord[];
